name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  ci:
    uses: selfshop-dev/lib-default-workflows/.github/workflows/ci.yml@main
    secrets: inherit