name: Security

on:
  schedule:
    - cron: '0 9 * * 1'
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security:
    uses: selfshop-dev/lib-default-workflows/.github/workflows/security.yml@main